### ISSUE TITLE
Error importing odd characters in MET CSV import

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#129]
```
2017-08-21T09:00:26-07:00  INFO traject (2.3.3) executing with: `-c config/traject.rb -c lib/traject/met_csv_config.rb /Users/amcollie/Temp/met_museum_records.csv`
2017-08-21T09:00:26-07:00  INFO Reading from /Users/amcollie/Temp/met_museum_records.csv
2017-08-21T09:00:26-07:00 FATAL Traject::CommandLine: Unexpected exception, terminating execution: #<ArgumentError: invalid byte sequence in UTF-8>
/Users/amcollie/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:2046:in `=~': invalid byte sequence in UTF-8 (ArgumentError)
	from /Users/amcollie/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:2046:in `init_separators'
	from /Users/amcollie/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:1559:in `initialize'
	from /Users/amcollie/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:1321:in `new'
	from /Users/amcollie/.rvm/rubies/ruby-2.4.1/lib/ruby/2.4.0/csv.rb:1321:in `parse'
	from /Users/amcollie/Projects/DLME/dlme/lib/traject/csv_reader.rb:12:in `initialize'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/gems/traject-2.3.3/lib/traject/indexer.rb:536:in `new'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/gems/traject-2.3.3/lib/traject/indexer.rb:536:in `reader!'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/gems/traject-2.3.3/lib/traject/indexer.rb:434:in `process'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/gems/traject-2.3.3/lib/traject/command_line.rb:67:in `execute'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/gems/traject-2.3.3/bin/traject:14:in `<top (required)>'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/bin/traject:23:in `load'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/bin/traject:23:in `<main>'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `eval'
	from /Users/amcollie/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by jcoyne** [comment]
@aaron-collier can this be closed?

**Comment by aaron-collier** [comment]
Yup, I think so so. These were in the file. Closing.
