### ISSUE TITLE
Look into application deprecation warnings

### ISSUE THREAD

**Issue by cbeer** [sul-dlss/dlme#1457]
I think these are the deprecations that are caused by something we're doing in this application:

```
DEPRECATION WARNING: Detected as custom thumbnail presenter; make sure it has a #render method that returns just the thumbnail image tag.
```

```
DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from block in _app_views_statistics__items_html_erb__4476632810141767126_558020 at /home/circleci/project/app/views/statistics/_items.html.erb:15)
```

```
DEPRECATION WARNING: facet_display_value is deprecated and will be removed from blacklight 8.0. (called from facet_display_value at /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300) (6 times); e.g.: 
    /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300:in `facet_display_value'
    /home/circleci/project/app/views/statistics/_items.html.erb:16
```

```
DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from block (2 levels) in _app_views_statistics__items_html_erb__4476632810141767126_558020 at /home/circleci/project/app/views/statistics/_items.html.erb:24)
```

```
DEPRECATION WARNING: facet_display_value is deprecated and will be removed from blacklight 8.0. (called from facet_display_value at /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300) (6 times); e.g.: 
    /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300:in `facet_display_value'
    /home/circleci/project/app/views/statistics/_items.html.erb:25
```

```
DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from block in _app_views_statistics__items_html_erb__4476632810141767126_558020 at /home/circleci/project/app/views/statistics/_items.html.erb:47)
```

```
DEPRECATION WARNING: facet_display_value is deprecated and will be removed from blacklight 8.0. (called from facet_display_value at /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300) (6 times); e.g.: 
    /home/circleci/project/vendor/bundle/ruby/2.7.0/gems/blacklight-7.22.2/app/helpers/blacklight/facets_helper_behavior.rb:300:in `facet_display_value'
    /home/circleci/project/app/views/statistics/_items.html.erb:48:in `block (2 levels)
```

```
DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from block in link_type_hierarchy at /home/circleci/project/app/helpers/application_helper.rb:12)
```
```
DEPRECATION WARNING: path_for_facet is deprecated and will be removed from blacklight 8.0. (called from block in _app_views_statistics__contributors_html_erb___4468251086022986141_787660 at /home/circleci/project/app/views/statistics/_contributors.html.erb:15)
```

```
DEPRECATION WARNING: has_thumbnail? is deprecated and will be removed from blacklight 8.0 (use IndexPresenter#thumbnail.exists?). (called from _app_views_catalog__show_with_viewer_html_erb___2105819727872697941_906680 at /home/circleci/project/app/views/catalog/_show_with_viewer.html.erb:13)
```

```
DEPRECATION WARNING: render_thumbnail_tag is deprecated and will be removed from blacklight 8.0 (Use IndexPresenter#thumbnail.thumbnail_tag). (called from block in _app_views_catalog__show_with_viewer_html_erb___2105819727872697941_906680 at /home/circleci/project/app/views/catalog/_show_with_viewer.html.erb:18) 
```

**Comment by cbeer** [comment]
I think the remaining deprecation warnings are all coming out of blacklight_range_limit
