### ISSUE TITLE
Forgot password link does not appear to be working

### ISSUE THREAD

**Issue by hudajkhan** [sul-dlss/dlme#1763]
On both dlme-stage and dlme-prod, clicking on "forgot password" and then entering your email address does not result in a password change message being sent.  The URL is https://dlme-stage.stanford.edu/users/password/new . On staging, clicking "send  me reset password instructions" takes one to the URL "https://dlme-stage.stanford.edu/users/password" with a Rails error page with the message "we're sorry, but something went wrong".  On dlme-prod, the page goes to https://library-status.stanford.edu/ instead.  In both cases, no email with password reset instructions is received at the email address that was input.

**Comment by hudajkhan** [comment]
Error below in logs:

I, [2023-03-16T15:55:15.720075 #2138651]  INFO -- : [b4382eba-af18-4d4d-9262-71515e795b50] Started POST "/users/password" for 10.130.12.112 at 2023-03-16 15:55:15 -0700
I, [2023-03-16T15:55:15.721240 #2138651]  INFO -- : [b4382eba-af18-4d4d-9262-71515e795b50] Processing by Devise::PasswordsController#create as HTML
I, [2023-03-16T15:55:15.721399 #2138651]  INFO -- : [b4382eba-af18-4d4d-9262-71515e795b50]   Parameters: {"authenticity_token"=>"[FILTERED]", "user"=>{"email"=>"hudakhan@stanford.edu"}, "commit"=>"Send me reset password instructions"}
I, [2023-03-16T15:55:15.860039 #2138651]  INFO -- : [b4382eba-af18-4d4d-9262-71515e795b50]   Rendered /opt/app/dlme/dlme/shared/bundle/ruby/3.2.0/gems/devise-4.9.0/app/views/devise/mailer/reset_password_instructions.html.erb (Duration: 3.7ms | Allocations: 422)
I, [2023-03-16T15:55:15.860541 #2138651]  INFO -- : [b4382eba-af18-4d4d-9262-71515e795b50] Completed 500 Internal Server Error in 139ms (ActiveRecord: 5.8ms | Allocations: 6345)
F, [2023-03-16T15:55:15.862180 #2138651] FATAL -- : [b4382eba-af18-4d4d-9262-71515e795b50]   
[b4382eba-af18-4d4d-9262-71515e795b50] ActionView::Template::Error (Missing host to link to! Please provide the :host parameter, set default_url_options[:host], or set :only_path to true):
[b4382eba-af18-4d4d-9262-71515e795b50]     2: 
[b4382eba-af18-4d4d-9262-71515e795b50]     3: <p>Someone has requested a link to change your password. You can do this through the link below.</p>
[b4382eba-af18-4d4d-9262-71515e795b50]     4: 
[b4382eba-af18-4d4d-9262-71515e795b50]     5: <p><%= link_to 'Change my password', edit_password_url(@resource, reset_password_token: @token) %></p>
[b4382eba-af18-4d4d-9262-71515e795b50]     6: 
[b4382eba-af18-4d4d-9262-71515e795b50]     7: <p>If you didn't request this, please ignore this email.</p>
[b4382eba-af18-4d4d-9262-71515e795b50]     8: <p>Your password won't change until you access the link above and create a new one.</p>
[b4382eba-af18-4d4d-9262-71515e795b50]   
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/http/url.rb:64:in `full_url_for'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/http/url.rb:54:in `url_for'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:334:in `block in <class:RouteSet>'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:846:in `url_for'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:271:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:327:in `block in define_url_helper'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/routes_proxy.rb:45:in `edit_user_password_url'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/routes_proxy.rb:48:in `public_send'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/routes_proxy.rb:48:in `method_missing'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/controllers/url_helpers.rb:53:in `block (4 levels) in generate_helpers!'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) app/views/devise/mailer/reset_password_instructions.html.erb:5
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/base.rb:244:in `public_send'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/base.rb:244:in `_run'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/template.rb:157:in `block in render'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:208:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/template.rb:361:in `instrument_render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/template.rb:155:in `render'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/template_renderer.rb:65:in `block (2 levels) in render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `block in instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/template_renderer.rb:60:in `block in render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/template_renderer.rb:79:in `render_with_layout'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/template_renderer.rb:59:in `render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/template_renderer.rb:11:in `render'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/renderer.rb:61:in `render_template_to_object'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/renderer/renderer.rb:29:in `render_to_object'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/rendering.rb:117:in `block in _render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/base.rb:270:in `in_rendering_context'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/rendering.rb:116:in `_render_template'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/rendering.rb:103:in `render_to_body'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/rendering.rb:25:in `render'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:992:in `block in collect_responses_from_templates'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:989:in `each'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:989:in `each'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:989:in `map'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:989:in `collect_responses_from_templates'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:967:in `collect_responses'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:875:in `mail'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/mailers/helpers.rb:19:in `devise_mail'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) app/mailers/devise/mailer.rb:14:in `reset_password_instructions'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/base.rb:215:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] actiontext (7.0.4.2) lib/action_text/rendering.rb:20:in `with_renderer'
[b4382eba-af18-4d4d-9262-71515e795b50] actiontext (7.0.4.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:233:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/base.rb:151:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:25:in `block in process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/rescuable.rb:24:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/rendering.rb:39:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:646:in `block in process'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `block in instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/base.rb:645:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:128:in `block in processed_mailer'
[b4382eba-af18-4d4d-9262-71515e795b50] <internal:kernel>:90:in `tap'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:127:in `processed_mailer'
[b4382eba-af18-4d4d-9262-71515e795b50] actionmailer (7.0.4.2) lib/action_mailer/message_delivery.rb:118:in `deliver_now'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/models/authenticatable.rb:204:in `send_devise_notification'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/models/recoverable.rb:99:in `send_reset_password_instructions_notification'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/models/recoverable.rb:52:in `send_reset_password_instructions'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) lib/devise/models/recoverable.rb:136:in `send_reset_password_instructions'
[b4382eba-af18-4d4d-9262-71515e795b50] devise (4.9.0) app/controllers/devise/passwords_controller.rb:15:in `create'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/base.rb:215:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/rendering.rb:53:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:234:in `block in process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:118:in `block in run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] actiontext (7.0.4.2) lib/action_text/rendering.rb:20:in `with_renderer'
[b4382eba-af18-4d4d-9262-71515e795b50] actiontext (7.0.4.2) lib/action_text/engine.rb:69:in `block (4 levels) in <class:Engine>'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `instance_exec'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:127:in `block in run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:138:in `run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/callbacks.rb:233:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/rescue.rb:22:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/instrumentation.rb:67:in `block in process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `block in instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications/instrumenter.rb:24:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/notifications.rb:206:in `instrument'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/instrumentation.rb:66:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal/params_wrapper.rb:259:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] activerecord (7.0.4.2) lib/active_record/railties/controller_runtime.rb:27:in `process_action'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/abstract_controller/base.rb:151:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionview (7.0.4.2) lib/action_view/rendering.rb:39:in `process'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal.rb:188:in `dispatch'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_controller/metal.rb:251:in `dispatch'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:49:in `dispatch'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:32:in `serve'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:18:in `block in <class:Constraints>'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/mapper.rb:48:in `serve'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:50:in `block in serve'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `each'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/journey/router.rb:32:in `serve'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/routing/route_set.rb:852:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack-attack (6.6.1) lib/rack/attack.rb:103:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack-attack (6.6.1) lib/rack/attack.rb:127:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] warden (1.2.9) lib/warden/manager.rb:36:in `block in call'
[b4382eba-af18-4d4d-9262-71515e795b50] warden (1.2.9) lib/warden/manager.rb:34:in `catch'
[b4382eba-af18-4d4d-9262-71515e795b50] warden (1.2.9) lib/warden/manager.rb:34:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/tempfile_reaper.rb:15:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/etag.rb:27:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/conditional_get.rb:40:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/head.rb:12:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/http/permissions_policy.rb:38:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/http/content_security_policy.rb:36:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/session/abstract/id.rb:266:in `context'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/session/abstract/id.rb:260:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/cookies.rb:704:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:27:in `block in call'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/callbacks.rb:99:in `run_callbacks'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack-timeout (0.6.3) lib/rack/timeout/core.rb:148:in `block in call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack-timeout (0.6.3) lib/rack/timeout/support/timeout.rb:19:in `timeout'
[b4382eba-af18-4d4d-9262-71515e795b50] rack-timeout (0.6.3) lib/rack/timeout/core.rb:147:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/debug_exceptions.rb:28:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/show_exceptions.rb:26:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] railties (7.0.4.2) lib/rails/rack/logger.rb:40:in `call_app'
[b4382eba-af18-4d4d-9262-71515e795b50] railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `block in call'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `block in tagged'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:37:in `tagged'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/tagged_logging.rb:99:in `tagged'
[b4382eba-af18-4d4d-9262-71515e795b50] railties (7.0.4.2) lib/rails/rack/logger.rb:25:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/remote_ip.rb:93:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] request_store (1.5.1) lib/request_store/middleware.rb:19:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/request_id.rb:26:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/method_override.rb:24:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/runtime.rb:22:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] activesupport (7.0.4.2) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/executor.rb:14:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] rack (2.2.6.3) lib/rack/sendfile.rb:110:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] actionpack (7.0.4.2) lib/action_dispatch/middleware/host_authorization.rb:131:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] honeybadger (5.2.0) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
[b4382eba-af18-4d4d-9262-71515e795b50] honeybadger (5.2.0) lib/honeybadger/agent.rb:433:in `with_rack_env'
[b4382eba-af18-4d4d-9262-71515e795b50] honeybadger (5.2.0) lib/honeybadger/rack/error_notifier.rb:30:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] honeybadger (5.2.0) lib/honeybadger/rack/user_feedback.rb:31:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] honeybadger (5.2.0) lib/honeybadger/rack/user_informer.rb:21:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] slowpoke (0.4.0) lib/slowpoke/middleware.rb:8:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] railties (7.0.4.2) lib/rails/engine.rb:530:in `call'
[b4382eba-af18-4d4d-9262-71515e795b50] /usr/lib/ruby/vendor_ruby/phusion_passenger/rack/thread_handler_extension.rb:107:in `process_request'
[b4382eba-af18-4d4d-9262-71515e795b50] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:157:in `accept_and_process_next_request'
[b4382eba-af18-4d4d-9262-71515e795b50] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler/thread_handler.rb:110:in `main_loop'
[b4382eba-af18-4d4d-9262-71515e795b50] /usr/lib/ruby/vendor_ruby/phusion_passenger/request_handler.rb:419:in `block (3 levels) in start_threads'
[b4382eba-af18-4d4d-9262-71515e795b50] /usr/lib/ruby/vendor_ruby/phusion_passenger/utils.rb:113:in `block in create_thread_and_abort_on_exception'

**Comment by hudajkhan** [comment]
Comparing against the old dev site (dev.dlmenetwork.org) where the email does work, I think what is happening is this:
Environment variables (not the .env file but variables set outside that) define actionsmtp_id, smtp_from, smtp_key, and keys that fall under SETTINGS__ACTION_MAILER__DEFAULT_URL_OPTIONS and SETTINGS__ACTION_MAILER__DEFAULT_OPTIONS (e.g. SETTINGS__ACTION_MAILER__DEFAULT_URL_OPTIONS__HOST and SETTINGS__ACTION_MAILER__DEFAULT_OPTIONS__FROM) .   The environment variables for settings are picked up by https://github.com/sul-dlss/dlme/blob/main/config/initializers/action_mailer.rb so they can be made available to the application as Settings.action_mailer_default_options and Settings.action_mailer.default_url_options (which are both hashes). 

https://github.com/sul-dlss/dlme/blob/main/config/initializers/action_mailer.rb is then able to read what it requires from Settings and the environment variables.

**Comment by hudajkhan** [comment]
None of these environment variables are returned from a printenv command on the dlme-stage server nor is there a .env file in the current or shared directories.

**Comment by hudajkhan** [comment]
It took a few tries but I am seeing the same error in the dlme-prod production log, and the environment variables are not set on dlme-prod either.

**Comment by hudajkhan** [comment]
Dlme-stage is now returning a forgot password message with the from address "sul-aws-dlme-monitor@lists.stanford.edu". The message follows this pattern: 
"Hello [recipient email]!

Someone has requested a link to change your password. You can do this through the link below.

Change my password(link). 

If you didn't request this, please ignore this email.

Your password won't change until you access the link above and create a new one."

**Comment by hudajkhan** [comment]
dlmenetwork.org (production) is now returning a forgot password message using the same from address and pattern below.  The change my password link goes to the correct server in both the stage and production cases.

**Comment by hudajkhan** [comment]
For reference, related puppet pull request: https://github.com/sul-dlss/puppet/pull/9285
