### ISSUE TITLE
Dev: trying to run all transforms leads to error:

### ISSUE THREAD

**Issue by anarchivist** [sul-dlss/dlme#468]
Steps to reproduce

* Go into dev -> Site administration -> Transform data
* Leave path field blank
* Click "Begin transform"
* Receive "We're sorry, but something went wrong."

Seems to trigger the following: https://app.honeybadger.io/projects/53082/faults/46255424 (see #432)

**Comment by justinlittman** [comment]
```
F, [2019-03-06T12:36:27.294068 #7] FATAL -- : [cbea6761-6072-4b58-9ac0-c62a83ec814e]
F, [2019-03-06T12:36:27.294134 #7] FATAL -- : [cbea6761-6072-4b58-9ac0-c62a83ec814e] Aws::SNS::Errors::InvalidParameter (Invalid parameter: Empty message):
F, [2019-03-06T12:36:27.294206 #7] FATAL -- : [cbea6761-6072-4b58-9ac0-c62a83ec814e]
F, [2019-03-06T12:36:27.294297 #7] FATAL -- : [cbea6761-6072-4b58-9ac0-c62a83ec814e] app/services/transform_notification.rb:10:in `publish'
[cbea6761-6072-4b58-9ac0-c62a83ec814e] app/services/transform_notification.rb:6:in `publish'
[cbea6761-6072-4b58-9ac0-c62a83ec814e] app/controllers/transforms_controller.rb:14:in `create'
[cbea6761-6072-4b58-9ac0-c62a83ec814e] lib/middleware/fix_sns_json_middleware.rb:13:in `call'
```
