### ISSUE TITLE
exporter chokes on some resources

### ISSUE THREAD

**Issue by jmartin-sul** [sul-dlss/dlme#600]
for example:
```
$ ./bin/export ucdavis
sinopia_exporter v0.3.0
beginning export of RDF from group: ucdavis
Sinopia Server client lazily instantiated.  base URL: https://trellis.sinopia.io
error saving resource ucdavis/afbe09ad-e05e-4463-91ac-3607a54b1800 to ./exported_rdf/ucdavis_2019-10-28T23:23:05.213Z : TypeError: data.map is not a function
    at Function.exports.convertToType (/Users/user/software_dev_projects/sinopia_exporter/node_modules/sinopia_server/src/ApiClient.js:531:23)
    at Function.exports.constructFromObject (/Users/user/software_dev_projects/sinopia_exporter/node_modules/sinopia_server/src/model/SinopiaResource.js:75:34)
    at Function.exports.convertToType (/Users/user/software_dev_projects/sinopia_exporter/node_modules/sinopia_server/src/ApiClient.js:527:23)
    at exports.deserialize (/Users/user/software_dev_projects/sinopia_exporter/node_modules/sinopia_server/src/ApiClient.js:350:20)
    at /Users/user/software_dev_projects/sinopia_exporter/node_modules/sinopia_server/src/ApiClient.js:473:30
    at Request.callback (/Users/user/software_dev_projects/sinopia_exporter/node_modules/superagent/lib/node/index.js:814:12)
    at /Users/user/software_dev_projects/sinopia_exporter/node_modules/superagent/lib/node/index.js:1036:18
    at IncomingMessage.<anonymous> (/Users/user/software_dev_projects/sinopia_exporter/node_modules/superagent/lib/node/parsers/json.js:19:7)
    at Stream.emit (events.js:210:5)
    at Stream.EventEmitter.emit (domain.js:476:20)
completed export of ucdavis at 2019-10-28T23:23:05.500Z
finished export of RDF from group: ucdavis
```

the resource from the above error:
https://trellis.sinopia.io/repository/ucdavis/afbe09ad-e05e-4463-91ac-3607a54b1800

```sh
$ curl -H 'Accept: application/ld+json' https://trellis.sinopia.io/repository/ucdavis/afbe09ad-e05e-4463-91ac-3607a54b1800 | jq
```
```json
{
  "@id": "",
  "@type": "schema:Thing",
  "description": {
    "@language": "en",
    "@value": "Thing of Things"
  },
  "identifier": {
    "@language": "en",
    "@value": "ark:/86290/d7654e"
  },
  "hasResourceTemplate": "sinopia:resourceTemplate:schema:Thing",
  "@context": {
    "description": {
      "@id": "http://schema.org/description"
    },
    "identifier": {
      "@id": "http://schema.org/identifier"
    },
    "hasResourceTemplate": {
      "@id": "http://sinopia.io/vocabulary/hasResourceTemplate"
    },
    "schema": "http://schema.org/",
    "owl": "http://www.w3.org/2002/07/owl#",
    "xsd": "http://www.w3.org/2001/XMLSchema#",
    "skos": "http://www.w3.org/2004/02/skos/core#",
    "memento": "http://mementoweb.org/ns#",
    "rdfs": "http://www.w3.org/2000/01/rdf-schema#",
    "acl": "http://www.w3.org/ns/auth/acl#",
    "geo": "http://www.w3.org/2003/01/geo/wgs84_pos#",
    "dc11": "http://purl.org/dc/elements/1.1/",
    "as": "https://www.w3.org/ns/activitystreams#",
    "rdf": "http://www.w3.org/1999/02/22-rdf-syntax-ns#",
    "ldp": "http://www.w3.org/ns/ldp#",
    "time": "http://www.w3.org/2006/time#",
    "prov": "http://www.w3.org/ns/prov#",
    "dc": "http://purl.org/dc/terms/"
  }
}
```

**Comment by anarchivist** [comment]
@jmartin-sul wrong repo?

**Comment by jmartin-sul** [comment]
@anarchivist yup, and can't move between orgs apparently, closing
