### ISSUE TITLE
S3 Fetch in Stage is broken

### ISSUE THREAD

**Issue by aaron-collier** [sul-dlss/dlme#755]
```
I, [2019-11-27T22:56:41.244773 #1]  INFO -- : [d03576fc-4056-4967-a1e4-9c2800346cff] method=POST path=/library/s3_harvester format=html controller=S3HarvesterController action=create status=500 error='NoMethodError: undefined method `[]' for true:TrueClass' duration=4923.45 view=0.00 db=8.63
F, [2019-11-27T22:56:41.245568 #1] FATAL -- : [d03576fc-4056-4967-a1e4-9c2800346cff]   
F, [2019-11-27T22:56:41.245751 #1] FATAL -- : [d03576fc-4056-4967-a1e4-9c2800346cff] NoMethodError (undefined method `[]' for true:TrueClass):
F, [2019-11-27T22:56:41.245793 #1] FATAL -- : [d03576fc-4056-4967-a1e4-9c2800346cff]   
F, [2019-11-27T22:56:41.245841 #1] FATAL -- : [d03576fc-4056-4967-a1e4-9c2800346cff] app/controllers/s3_harvester_controller.rb:29:in `block in any_duplicate_identifiers?'
[d03576fc-4056-4967-a1e4-9c2800346cff] app/controllers/s3_harvester_controller.rb:28:in `map'
[d03576fc-4056-4967-a1e4-9c2800346cff] app/controllers/s3_harvester_controller.rb:28:in `any_duplicate_identifiers?'
[d03576fc-4056-4967-a1e4-9c2800346cff] app/controllers/s3_harvester_controller.rb:14:in `create'
I, [2019-11-27T22:56:41.246624 #1]  INFO -- honeybadger: ** [Honeybadger] Reporting error id=555f0ece-169a-4c4c-99db-3bcae2b7b7b0 level=1 pid=1
W, [2019-11-27T22:56:41.512757 #1]  WARN -- honeybadger: ** [Honeybadger] Error report failed: project is sending too many errors. id=555f0ece-169a-4c4c-99db-3bcae2b7b7b0 code=429 throttle=1 interval=0.05 level=2 pid=1
```

**Comment by aaron-collier** [comment]
Fixed.
