### ISSUE TITLE
Error trying to load record

### ISSUE THREAD

**Issue by jacobthill** [sul-dlss/dlme#867]
Trying to load the following record:

```{"cho_title":{"ar-Arab":["شرح تشريح الأفلاك - سهارنفوري، عصمة الله بن أعظم، والإجابة على تعليق الجونبوري - لندني، حسين"],"en":["Sharḥ tashrīḥ al-aflāk شرح تشريح الأفلاك  Sahāranfūrī, ʿIṣmat Allāh ibn Aʿẓam سهارنفوري، عصمة الله بن أعظم  and  al-Ijābah ʿalá taʿlīq al-Jawnbūrī الإجابة على تعليق الجونبوري  Landanī, Ḥusayn لندني، حسين"]},"cho_date":{"none":["1830/1830"]},"cho_date_range_norm":[1830],"cho_date_range_hijri":[1245,1246],"cho_dc_rights":{"ar-Arab":["المُلكية العامة"],"en":["Public Domain"]},"cho_description":{"ar-Arab":["(١) السهارنفوري، شرح تشريح الأفلاك\n                           (صص. ١و-١٢٩ظ)؛(٢) اللندني، الإجابة على تعليق الجونبوري\n                           (صص. ١٣٠و-١٤١و).تحتوي الأوراق ١٤١و، السطر ٣-١٤٥ظ على عدة ملاحظات ومقتطفات بالفارسية.","كوديكس؛ صص. v+ ١٤٧ +v","المادة: ورق مسلّك شرقيالأبعاد: حجم الورقة ٢٨٥ × ١٧٠ مم [مساحة الكتابة ٢٥٠ × ١٠٠ مم]ترقيم الأوراق: ترقيم عربي شرقي في وسط حاشية الرأس؛ ترقيم الأوراق الخاص بمكتبة مكتب الهند مختوم بالحبر الأسودالتسطير:\n                           مسطرة؛ ١٥-١٨ سطرًا في كل صفحة؛ مسافة تباعد عمودية ٨-٩ أسطر لكل ١٠ سمالخط:\n                           نستعليق؛ الناسخ هو محمد تقي (انظر ص. ١٢٩ظ، الأسطر ١٥-١٧).الحبر: حبر أسود، مع تحمير العناوين والخطوط الأفقية أعلى النص والرسوم البيانيةالزخرفة: لا يوجدالتجليد: تجليد مصنوع من الجلد بالكامل، مع إطارات ملونة وجامة وأذيال جامات وزوايا مزخرفة مختومة؛ دعائم للخياطة موجودة داخل الغلافين؛ مدرّجتان أصليتانالحالة: يوجد تلف كبير بالغلافين بسبب الحشرات؛ وتلف بسيط في قالب الكتاب ناتج عن الحشراتالحاشية: بأكثر من يدالأختام: صص. ١و، ١٤٥ظ"],"en":["(1) al-Sahāranfūrī (السهارنفوري),\n                           Sharḥ tashrīḥ al-aflāk(شرح تشريح الأفلاك; ff. 1r-129v);(2) al-Landanī (اللندني),\n                           al-Ijābah ʿalá taʿ\n                           līq al-Jawnbūrī(الإجابة على تعليق الجونبوري; ff. 130r-141r).Folios 141r, line 3-145v contain various Persian notes and extracts.","Codex; ff. v+147+v","Material: Eastern laid paperDimensions: 285 x 170 mm leaf [250 x 100 mm written]Foliation: Eastern Arabic foliation at centre of head margin; India Office Library foliation stamped in black inkRuling:\n                           Misṭarah; 15-18 lines per page; vertical spacing 8-9 lines per 10 cmScript:\n                           Nasta‘līq; the scribe is Muḥammad Taqī (محمد تقي, see f. 129v, lines 15-17).Ink: Black ink, with rubricated headings and diagrams and overlinings in redDecoration: NoneBinding: Full leather binding, with painted borders and stamped medallion, pendants and corner pieces; sewing supports visible on insides of both boards; original end bandsCondition: Extensive insect damage to boards; minor insect damage to book blockMarginalia: By more than one handSeals: ff. 1r and 145v"]},"cho_edm_type":{"ar-Arab":["نص"],"en":["Text"]},"cho_extent":{"ar-Arab":["كوديكس؛ صص. v+ ١٤٧ +v"],"en":["Codex; ff. v+147+v"]},"cho_has_type":{"ar-Arab":["مخطوطة"],"en":["Manuscript"]},"cho_identifier":["81055/vdc_100042759510.0x000001_ar","81055/vdc_100042759510.0x000001_en","Delhi Arabic 1928"],"cho_is_part_of":{"ar-Arab":["المكتبة البريطانية: مخطوطات شرقية"],"en":["British Library: Oriental Manuscripts"]},"cho_language":{"ar-Arab":["العربية"],"en":["Arabic"]},"cho_subject":{"ar-Arab":["الفلك-- أعمال ما قبل سنة ١٨٠٠"],"en":["Astronomy--Early works to 1800"]},"cho_type":{"ar-Arab":["مخطوطة"],"en":["Manuscript"]},"agg_data_provider":{"en":["British Library. India Office Records and Private Papers"],"ar-Arab":["المكتبة البريطانية، سجلات مكتب الهند والأوراق الخاصة"]},"agg_data_provider_country":{"en":["United Kingdom"],"ar-Arab":["المملكة المتحدة"]},"agg_provider":{"en":["Qatar National Library"],"ar-Arab":["مكتبة قطر الوطنية"]},"agg_provider_country":{"en":["Qatar"],"ar-Arab":["قطر"]},"cho_type_facet":{"ar-Arab":["نص","نص:مخطوطة"],"en":["Text","Text:Manuscript"]},"id":"81055/vdc_100042759510.0x000001_dlme","transform_version":"02cb0b2","transform_timestamp":"2020-03-10 16:21:26 +0000","agg_data_provider_collection":"qnl/british-library-combined/data","dlme_source_file":"data/qnl/british-library-combined/data/qnl-combined-58.xml","agg_is_shown_at":{"wr_is_referenced_by":["https://www.qdl.qa/en/iiif/81055/vdc_100042759510.0x000001/manifest"],"wr_id":"http://www.qdl.qa/en/archive/81055/vdc_100042759510.0x000001"},"agg_preview":{"wr_is_referenced_by":["https://www.qdl.qa/en/iiif/81055/vdc_100042759510.0x000001/manifest"],"wr_id":"https://images.qdl.qa/iiif/images/81055/vdc_100042759510.0x000001/Delhi%20Arabic%201928_0001.jp2/full/!1000,1000/0/default.jpg"}}```

 in a local instance of thee dlme app results in the following error"

```activesupport (5.2.4.1) lib/active_support/core_ext/object/blank.rb:122:in `blank?'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:102:in `reject'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:102:in `convert_stored_value_to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:66:in `block in custom_fields_data_to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:62:in `each'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:62:in `each_with_object'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:62:in `custom_fields_data_to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:58:in `data_to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/spotlight/solr_document_sidecar.rb:22:in `to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/concerns/spotlight/solr_document.rb:94:in `block in to_solr'
activerecord (5.2.4.1) lib/active_record/relation/delegation.rb:71:in `each'
activerecord (5.2.4.1) lib/active_record/relation/delegation.rb:71:in `each'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/concerns/spotlight/solr_document.rb:94:in `inject'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/models/concerns/spotlight/solr_document.rb:94:in `to_solr'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/controllers/spotlight/solr_controller.rb:45:in `block in solr_documents'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/controllers/spotlight/solr_controller.rb:37:in `map'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/controllers/spotlight/solr_controller.rb:37:in `solr_documents'
/Users/jtim/.rbenv/versions/2.5.3/lib/ruby/gems/2.5.0/bundler/gems/spotlight-22884da863b9/app/controllers/spotlight/solr_controller.rb:21:in `update'
actionpack (5.2.4.1) lib/action_controller/metal/basic_implicit_render.rb:6:in `send_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:194:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rendering.rb:30:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:42:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:132:in `run_callbacks'
actionpack (5.2.4.1) lib/abstract_controller/callbacks.rb:41:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/rescue.rb:22:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `block in instrument'
activesupport (5.2.4.1) lib/active_support/notifications/instrumenter.rb:23:in `instrument'
activesupport (5.2.4.1) lib/active_support/notifications.rb:168:in `instrument'
actionpack (5.2.4.1) lib/action_controller/metal/instrumentation.rb:32:in `process_action'
actionpack (5.2.4.1) lib/action_controller/metal/params_wrapper.rb:256:in `process_action'
activerecord (5.2.4.1) lib/active_record/railties/controller_runtime.rb:24:in `process_action'
actionpack (5.2.4.1) lib/abstract_controller/base.rb:134:in `process'
actionview (5.2.4.1) lib/action_view/rendering.rb:32:in `process'
actionpack (5.2.4.1) lib/action_controller/metal.rb:191:in `dispatch'
actionpack (5.2.4.1) lib/action_controller/metal.rb:252:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:52:in `dispatch'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:34:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
railties (5.2.4.1) lib/rails/railtie.rb:190:in `public_send'
railties (5.2.4.1) lib/rails/railtie.rb:190:in `method_missing'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:19:in `block in <class:Constraints>'
actionpack (5.2.4.1) lib/action_dispatch/routing/mapper.rb:48:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:52:in `block in serve'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `each'
actionpack (5.2.4.1) lib/action_dispatch/journey/router.rb:35:in `serve'
actionpack (5.2.4.1) lib/action_dispatch/routing/route_set.rb:840:in `call'
rack-attack (6.2.2) lib/rack/attack.rb:156:in `call'
rack-attack (6.2.2) lib/rack/attack.rb:170:in `call'
warden (1.2.8) lib/warden/manager.rb:36:in `block in call'
warden (1.2.8) lib/warden/manager.rb:34:in `catch'
warden (1.2.8) lib/warden/manager.rb:34:in `call'
rack (2.2.2) lib/rack/tempfile_reaper.rb:15:in `call'
rack (2.2.2) lib/rack/etag.rb:27:in `call'
rack (2.2.2) lib/rack/conditional_get.rb:40:in `call'
rack (2.2.2) lib/rack/head.rb:12:in `call'
actionpack (5.2.4.1) lib/action_dispatch/http/content_security_policy.rb:18:in `call'
rack (2.2.2) lib/rack/session/abstract/id.rb:266:in `context'
rack (2.2.2) lib/rack/session/abstract/id.rb:260:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/cookies.rb:670:in `call'
activerecord (5.2.4.1) lib/active_record/migration.rb:559:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:28:in `block in call'
activesupport (5.2.4.1) lib/active_support/callbacks.rb:98:in `run_callbacks'
actionpack (5.2.4.1) lib/action_dispatch/middleware/callbacks.rb:26:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:151:in `block in call'
rack-timeout (0.6.0) lib/rack/timeout/support/timeout.rb:19:in `timeout'
rack-timeout (0.6.0) lib/rack/timeout/core.rb:150:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/debug_exceptions.rb:61:in `call'
web-console (3.7.0) lib/web_console/middleware.rb:135:in `call_app'
web-console (3.7.0) lib/web_console/middleware.rb:30:in `block in call'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `catch'
web-console (3.7.0) lib/web_console/middleware.rb:20:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.4.1) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `block in call'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `block in tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:28:in `tagged'
activesupport (5.2.4.1) lib/active_support/tagged_logging.rb:71:in `tagged'
railties (5.2.4.1) lib/rails/rack/logger.rb:26:in `call'
sprockets-rails (3.2.1) lib/sprockets/rails/quiet_assets.rb:13:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
request_store (1.5.0) lib/request_store/middleware.rb:19:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/request_id.rb:27:in `call'
rack (2.2.2) lib/rack/method_override.rb:24:in `call'
rack (2.2.2) lib/rack/runtime.rb:22:in `call'
activesupport (5.2.4.1) lib/active_support/cache/strategy/local_cache_middleware.rb:29:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/executor.rb:14:in `call'
actionpack (5.2.4.1) lib/action_dispatch/middleware/static.rb:127:in `call'
rack (2.2.2) lib/rack/sendfile.rb:110:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/error_notifier.rb:33:in `block in call'
honeybadger (4.5.6) lib/honeybadger/agent.rb:397:in `with_rack_env'
honeybadger (4.5.6) lib/honeybadger/rack/error_notifier.rb:30:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/user_feedback.rb:31:in `call'
honeybadger (4.5.6) lib/honeybadger/rack/user_informer.rb:21:in `call'
slowpoke (0.3.2) lib/slowpoke/middleware.rb:8:in `call'
webpacker (4.2.2) lib/webpacker/dev_server_proxy.rb:23:in `perform_request'
rack-proxy (0.6.5) lib/rack/proxy.rb:57:in `call'
railties (5.2.4.1) lib/rails/engine.rb:524:in `call'
puma (3.12.4) lib/puma/configuration.rb:227:in `call'
puma (3.12.4) lib/puma/server.rb:675:in `handle_request'
puma (3.12.4) lib/puma/server.rb:476:in `process_client'
puma (3.12.4) lib/puma/server.rb:334:in `block in run'
puma (3.12.4) lib/puma/thread_pool.rb:135:in `block in spawn_thread'
Request
Parameters:
{"utf8"=>"✓",
 "authenticity_token"=>"pBerqmmlAQWz35Q5KLg4PMC0UlBAbpNgq+HntZnt4sPG7JGmBD1ToaAXFnKddFjdDBNzPVbdPRLqRCsmQCMROQ==",
 "resources_json_upload"=>
  {"json"=>
    #<ActionDispatch::Http::UploadedFile:0x00007fc9abf2fec8
     @content_type="application/octet-stream",
     @headers=
      "Content-Disposition: form-data; name=\"resources_json_upload[json]\"; filename=\"output-98f418c2-078c-45f7-a5b8-f16c7631edd6.ndjson\"\r\n" + "Content-Type: application/octet-stream\r\n",
     @original_filename="output-98f418c2-078c-45f7-a5b8-f16c7631edd6.ndjson",
     @tempfile=#<File:/var/folders/p9/q55b0d6j3pg8zvd9bxyz3x_c0000gr/T/RackMultipart20200310-25728-owxqd8.ndjson>>},
 "commit"=>"Add item",
 "exhibit_id"=>"dlme"}```

To reproduce run: 

```
docker run --rm -e SKIP_FETCH_DATA=true \
                -v $(pwd)/.:/opt/traject \
                -v $(pwd)/../dlme-metadata:/opt/traject/data \
                -v $(pwd)/output:/opt/traject/output \
                suldlss/dlme-transform:latest \
                qnl/british-library-combined/data/qnl-combined-58.xml
``` 

and load in local instance of dlme app.

**Comment by jacobthill** [comment]
We need to try to load this through an S3 url. The error above might have been caused by trying to load the record another way.

**Comment by jacobthill** [comment]
Update: loading via S3 url solved the problem above. The records loaded locally as expected (17244 out of 17259 loaded; the ones that didn't load are believed to have data errors). The records will not load in stage or dev completely. Only 12,582 records load. This is possibly related to https://github.com/sul-dlss/dlme/issues/866.

**Comment by jacobthill** [comment]
@aaron-collier reported being able to load 16,779 records into dev when splitting the data into chunks of 1000 so this may be a resource problem. The raw data for Cambridge is the same size though, and the IR is much larger and it loads fine without breaking it into smaller chunks.
